### PR TITLE
Refactor part2

### PR DESCRIPTION
**Pull request by kevxo**
Basically what I did here is add tests to the classes that didn't have a test and organized some tests. Didn't do mocks and stubs, because it wasn't for me.

### CODE REVIEW

**Comment by ShaunDaneJames** [comment]
LGTM!!!

**Comment by Oxalisviolacea** [comment]
LGTM!!

**Comment by Oxalisviolacea** [comment]
https://giphy.com/gifs/computer-money-working-2WuHHWbGt3fY4

**Comment by Oxalisviolacea** [comment]
(https://giphy.com/gifs/computer-money-working-2WuHHWbGt3fY4)

**Comment by carson-jardine** [comment]
LGTM!!!!!!

**Pull request merged**
